<a href="https://colab.research.google.com/github/majaVtech/car-price-prediction/blob/main/Notebooks/o1_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task - Used car price prediction
In this part of the processing, we will investigate the composition of the dataset, whether there are missing values, invalid values, extreme values, etc. We will also familiarize ourselves with all types of data that our dataset contains.

### Step 1: Loading the dataset

Here I will gather all the necessary information about the dataset to get started.

I have shown the shape of the dataset, rows and columns.
Information about the dataset, what to expect from the dataset, what data type, column name, number of columns, index range and a preview of the dataset through a few random rows.

In [4]:
import pandas as pd

url = "https://raw.githubusercontent.com/majaVtech/car-price-prediction/main/Data/cars.csv"
df = pd.read_csv(url)

print("Shape of the dataset:", df.shape)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("=" * 40)

print("\nDataset information:")
df.info()

print("=" * 40)
print("\nReview of the dataset:")
df.head()
df.sample(5, random_state=42)

Shape of the dataset: (56244, 12)
Rows: 56244
Columns: 12
========================================

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56244 entries, 0 to 56243
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   make                 56244 non-null  object
 1   model                56244 non-null  object
 2   priceUSD             56244 non-null  int64
 3   year                 56244 non-null  int64
 4   condition            56244 non-null  object
 5   mileage(kilometers)  56244 non-null  float64
 6   fuel_type            56244 non-null  object
 7   volume(cm3)          56197 non-null  float64
 8   color                56244 non-null  object
 9   transmission         56244 non-null  object
 10  drive_unit           54339 non-null  object
 11  segment              50953 non-null  object
dtypes: float64(2), int64(2), object(8)
memory usage: 5.1+ MB
========================================

Review of the dataset:

,make,model,priceUSD,year,condition,mileage(kilometers),fuel_type,volume(cm3),color,transmission,drive_unit,segment
19270,mitsubishi,carisma,2050,1999,with mileage,250000.0,petrol,1800.0,blue,mechanics,front-wheel drive,M
25927,ford,fusion,4500,2006,with mileage,160000.0,petrol,1400.0,burgundy,mechanics,front-wheel drive,M
23388,mercedes-benz,e-klass,3500,1999,with mileage,485000.0,diesel,2900.0,blue,mechanics,rear drive,E
53189,bmw,x3,21000,2013,with mileage,159000.0,diesel,2000.0,black,auto,NaN,J
34058,renault,megane,3990,2002,with mileage,331700.0,diesel,1900.0,other,mechanics,front-wheel drive,C

In [5]:
print("\nList of columns:")
df.columns.to_list()

List of columns:

['make',
 'model',
 'priceUSD',
 'year',
 'condition',
 'mileage(kilometers)',
 'fuel_type',
 'volume(cm3)',
 'color',
 'transmission',
 'drive_unit',
 'segment']

Showing the number of missing values ​​in the dataset

In [6]:
print("\nMissing values: ")
missing_values = df.isna().sum()
missing_values[missing_values>0]

Missing values:

volume(cm3)      47
drive_unit     1905
segment        5291
dtype: int64

Acquaintance with the column is of **great importance**, what values ​​are in it, extreme values ​​(minimum and maximum values) as well as the type of column.

In [7]:
print("\nReview of column of main interes:")
print(df['priceUSD'].head(10))
print("*" * 40)
print("Minimal value:", df['priceUSD'].min())
print("Maximum value:", df['priceUSD'].max())
print("-" * 40)
print("Data type of column:", df['priceUSD'].dtype)

Review of column of main interes:
0    5500
1    5350
2    7000
3    3300
4    5200
5    3400
6    5000
7    7300
8    6400
9    6132
Name: priceUSD, dtype: int64
****************************************
Minimal value: 48
Maximum value: 235235
----------------------------------------
Data type of column: int64

Here we make sure that the missing values ​​belong to one of the values ​​from the set `missing_like_values`.

In [8]:
missing_like_values = ["NaN", "nan", "NULL", "null", "None", "none", "", " "]

for column in df.columns:
    if df[column].dtype == "object" or "float64" or "Int64":
        count = df[column].astype(str).str.strip().isin(missing_like_values).sum()
        if count > 0:
            print(f"{column}: {count}")

volume(cm3): 47
drive_unit: 1905
segment: 5291

Overview of all `numeric columns`

In [9]:
numeric_columns = [
    "mileage(kilometers)",
    "volume(cm3)",
    "year",
    "priceUSD"
]

df[numeric_columns].dtypes
df[numeric_columns].describe().round(2)

       mileage(kilometers)  volume(cm3)      year   priceUSD
count             56244.00     56197.00  56244.00   56244.00
mean             244395.63      2104.86   2003.45    7415.46
std              321030.67       959.20      8.14    8316.96
min                   0.00       500.00   1910.00      48.00
25%              137000.00      1600.00   1998.00    2350.00
50%              228500.00      1996.00   2004.00    5350.00
75%              310000.00      2300.00   2010.00    9807.50
max             9999999.00     20000.00   2019.00  235235.00

Overview of all `categorical_columns`

Here we checked all the unique values ​​found in the columns

In [10]:
categorical_columns = [
    "make",
    "model",
    "condition",
    "fuel_type",
    "color",
    "transmission",
    "drive_unit",
    "segment"
]

for column in categorical_columns:
    print(column)
    print(df[column].nunique())
    print("-" * 40)

make
96
----------------------------------------
model
1034
----------------------------------------
condition
3
----------------------------------------
fuel_type
3
----------------------------------------
color
13
----------------------------------------
transmission
2
----------------------------------------
drive_unit
4
----------------------------------------
segment
9
----------------------------------------

Here we got a detailed insight into all the values ​​found in the categorical columns (objects).

In [11]:
for column in categorical_columns:
    print(df[column].value_counts(dropna=False))
    print("-" * 40)

make
volkswagen    6861
audi          4030
bmw           4013
opel          3779
renault       3713
              ...
mclaren          1
asia             1
jac              1
tagaz            1
saipa            1
Name: count, Length: 96, dtype: int64
----------------------------------------
model
passat      2086
5-seriya    1476
a6          1276
golf        1070
astra       1013
            ...
x-90           1
xjs            1
180            1
88             1
33             1
Name: count, Length: 1034, dtype: int64
----------------------------------------
condition
with mileage    55278
with damage       512
for parts         454
Name: count, dtype: int64
----------------------------------------
fuel_type
petrol        36405
diesel        19792
electrocar       47
Name: count, dtype: int64
----------------------------------------
color
black       12385
silver      10075
blue         8083
gray         5807
white        5292
green        3911
other        3397
red          2744
burgundy     2026
brown        1349
purple        625
yellow        317
orange        233
Name: count, dtype: int64
----------------------------------------
transmission
mechanics    36056
auto         20188
Name: count, dtype: int64
----------------------------------------
drive_unit
front-wheel drive             38016
rear drive                     6836
all-wheel drive                5890
part-time four-wheel drive     3597
NaN                            1905
Name: count, dtype: int64
----------------------------------------
segment
D      12605
C      10617
J       8629
M       6313
E       6274
NaN     5291
B       4393
F        896
S        765
A        461
Name: count, dtype: int64
----------------------------------------

Investigation of extreme values ​​by numerical columns.

In [12]:
numeric_columns = df.select_dtypes(include="number").columns

print(numeric_columns)

for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]

    print(f"\nColumn: {col}")
    print(f"Lower limit: {lower_bound:.2f}")
    print(f"Upper limit: {upper_bound:.2f}")
    print(f"Number of extreme values: {len(outliers)}")

    print(outliers[[col]].head(10))

Index(['priceUSD', 'year', 'mileage(kilometers)', 'volume(cm3)'], dtype='object')

Column: priceUSD
Lower limit: -8836.25
Upper limit: 20993.75
Number of extreme values: 2551
     priceUSD
302     22000
314     29990
381     21000
422     32000
424     22100
429     23999
434     21900
486     21900
521     23292
541     26800

Column: year
Lower limit: 1980.00
Upper limit: 2028.00
Number of extreme values: 258
     year
856  1964
857  1966
858  1966
859  1962
860  1965
861  1963
862  1966
863  1961
864  1965
865  1969

Column: mileage(kilometers)
Lower limit: -122500.00
Upper limit: 569500.00
Number of extreme values: 689
      mileage(kilometers)
695              999999.0
771             2500000.0
844              999999.0
876              999999.0
893             1111111.0
957             1112356.0
968              635940.0
983             1111111.0
1112            1111111.0
1113            3700490.0

Column: volume(cm3)
Lower limit: 550.00
Upper limit: 3350.00
Number of extreme values: 3618
      volume(cm3)
81        20000.0
354       20000.0
929       16000.0
1449        500.0
1537      20000.0
1566       3800.0
1569       4200.0
1768      20000.0
2037        500.0
2144      18000.0

Checking for duplicates

In [13]:
duplicate_count = df.duplicated().sum()

print("Number of completely duplicated rows:", duplicate_count)
print(f"Percentage of completely duplicated rows: {duplicate_count / len(df) * 100:.2f}%")

Number of completely duplicated rows: 87
Percentage of completely duplicated rows: 0.15%

Checking for ivalid values in numerical data.

In [14]:
print("Negative prices:", (df["priceUSD"] < 0).sum())
print("Negative mileage:", (df["mileage(kilometers)"] < 0).sum())
print("Negative engine volume:", (df["volume(cm3)"] < 0).sum())
print("Invalid years:", (df["year"] <= 0).sum())

print("Minimum year:", df["year"].min())
print("Maximum year:", df["year"].max())

invalid_years = df[
    (df["year"] < 1900) |
    (df["year"] > 2026)
]

display(invalid_years)

Negative prices: 0
Negative mileage: 0
Negative engine volume: 0
Invalid years: 0
Minimum year: 1910
Maximum year: 2019

Empty DataFrame
Columns: [make, model, priceUSD, year, condition, mileage(kilometers), fuel_type, volume(cm3), color, transmission, drive_unit, segment]
Index: []